services:
  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/var/www/html/www/index.html
